stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - dotnet build shariaty-course.sln

test:
  stage: test
  script:
    - dotnet test test-shariaty-course/test-shariaty-course.csproj

deploy:
  stage: deploy
  script:
    - dotnet publish shariaty-course/shariaty-course.csproj --configuration Release --output ./publish
    - echo "Deploying to Netlify..."
    - echo "Deploying to local server..."
    - dotnet run --project shariaty-course/shariaty-course.csproj --urls "http://localhost:8087"
